on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.12.9, 1.13]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Test
      run: go test ./...
      env:
        AWS_SNS_ENDPOINT: http://localhost:4575
        AWS_SQS_ENDPOINT: http://localhost:4576
        AWS_ACCESS_KEY_ID: foo
        AWS_SECRET_ACCESS_KEY: bar
