name: Go
on: [push]
jobs:

  build:

    name: Build
    runs-on: ubuntu-latest

    services:
      localstack:
        image: localstack/localstack:0.10.2
        env:
          SERVICES: sqs,sns
          AWS_ACCESS_KEY_ID: foo
          AWS_SECRET_ACCESS_KEY: bar
        ports:
        - 4575:4575
        - 4576:4576
        options: --health-cmd "aws --region eu-west-1 --endpoint=http://localhost:4576 sqs list-queues && aws --region eu-west-1 --endpoint=http://localhost:4575 sns list-topics" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Test
      run: go test -v ./...
      env:
        AWS_ACCESS_KEY_ID: foo
        AWS_SECRET_ACCESS_KEY: bar
        AWS_SNS_ENDPOINT: http://localhost:${{ job.services.localstack.ports[4575] }}
        AWS_SQS_ENDPOINT: http://localhost:${{ job.services.localstack.ports[4576] }}
